credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
            id: "dbd46277-3341-4268-8a73-307d816cfcf5"
            password: "{AQAAABAAAAAwJaksRHqW1RvyQLUvE6IDoCGS+7nrOLbSY+f4k6IfmojZP8DjzGqPZNfk+iGXonstvhc7Xl6PwHwY61x7SSkO6g==}"
            scope: GLOBAL
            username: "alpekin98"
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
unclassified:
  location:
    url: http://localhost:8080/
jobs:
  - script: >
      pipelineJob('self-study-cpp') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/alpekin98/self-study-2.git')
                }
                branch('*/main')
              }
            }
            lightweight()
          }
        }
      }
