jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
unclassified:
  location:
    url: http://192.168.55.10:8080/
jobs:
  - script: >
      pipelineJob('self-study-cpp') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/alpekin98/self-study-2.git')
                }
                branch('*/main')
              }
            }
            lightweight()
          }
        }
      }
      job('dependency-deb-package') {
        definition{
          steps {
            echo "dependency-deb-package"
            sh "echo 'Testing dependency-deb-package'"
          }
        }
      }
