services:
  cpp:
    image: cpp
    build:
      context: .
      dockerfile: Dockerfile-cpp
    ports:
      - 8081:80
  jenkins:
    image: jenkins_image
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    privileged: true
    user: root
    ports:
      - 8082:8080
