services:
  cpp:
    image: cpp
    build:
      context: .
      dockerfile: Dockerfile-cpp
    privileged: true
    user: root
    ports:
      - 8081:80
  jenkins:
    image: jenkins_image
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
    networks:
      mynet:
        ipv4_address: 192.168.55.10
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
