# Get Jenkins image
FROM jenkins/jenkins:lts
USER root

LABEL Name="jenkins-dockerfile"
LABEL version="1.0"

# RUN apt-get update -y
# RUN apt-get install make
# RUN apt-get install g++ -y
RUN apt-get update -y
RUN apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update
RUN apt-get install docker-ce docker-ce-cli containerd.io -y
RUN service docker start
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml

RUN echo 'ant:latest'  >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'antisamy-markup-formatter:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'build-timeout:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'cloudbees-folder:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'configuration-as-code:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'credentials-binding:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'email-ext:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'git:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'github-branch-source:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'gradle:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'ldap:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'mailer:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'matrix-auth:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'pam-auth:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'pipeline-github-lib:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'pipeline-stage-view:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'ssh-slaves:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'timestamper:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'workflow-aggregator:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'ws-cleanup:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'job-dsl:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'docker-plugin:latest' >> /usr/share/jenkins/ref/plugins.txt
RUN echo 'docker-workflow:latest' >> /usr/share/jenkins/ref/plugins.txt

# # casc.yaml Dosyası ....
# RUN echo -e '
# jenkins:
#   securityRealm:
#     local:
#       allowsSignup: false
#       users:
#         - id: admin
#           password: admin
# unclassified:
#   location:
#     url: http://192.168.55.10:8080/
#   globalLibraries:
#     libraries:
#       - name: "stage-hooks"
#         retriever:
#           modernSCM:
#             scm:
#               git:
#                 remote: "https://github.com/alpekin98/jenkins-shared-library-sample"
# jobs:
#   - script: >
#       pipelineJob("self-study-cpp") {
#         definition {
#           cpsScm {
#             scm {
#               git {
#                 remote {
#                   url("https://github.com/alpekin98/self-study-2.git")
#                 }
#                 branch("*/main")
#               }
#             }
#             lightweight()
#           }
#         }
#       }

# ' > /var/jenkins_home/casc.yaml

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml