FROM ubuntu:xenial
# docker rm -f ccc && docker run -v /var/run/docker.sock:/var/run/docker.sock -d --name ccc f16f839b952b4f7bd9bbf57038ff8b077422867a && docker exec -it ccc sh
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Istanbul

USER root

LABEL version="1.0"
LABEL Name="gtest-dockerfile"

RUN apt update
RUN apt install -y gcc\
 libgtest-dev\
 curl\
 dpkg\
 git\
 make\
 tzdata\
 cmake\
 build-essential

WORKDIR /usr/src/gtest
RUN cmake CMakeLists.txt

RUN make
RUN cp *.a /usr/lib