services:
  jenkins:
    image: jenkins_image
    volumes:
      - ./volume_jenkins:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
    networks:
      mynet:
        ipv4_address: 192.168.55.10
  # docker-registry:
  #   container_name: docker-registry
  #   image: alpekin98/demo-repo
  #   ports:
  #     - 5000:5000
  #   restart: always
  #   volumes:
  #     - ./volume:/var/lib/registry
  #   networks:
  #     mynet:
  #       ipv4_address: 192.168.55.11
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
